development:
  adapter: async

test:
  adapter: async

# production:
#   adapter: redis
#   url: <%= ENV['REDIS_URL'] %>

local: &local
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
